# Site settings
title: Highlights
email: jimv1.3@gmail.com
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jim_vance

# Build settings
name: Jim Vance
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
